# --------------------------------------------------------
#   File:         PR_Review_Automation.yaml
#   Author:       Codey Funston [s222250824@deakin.edu.au]
# 
#   Description:  Creates Azure DevOps task for each PR
#                 in repo. Randomly assigns a team 
#                 member to review.
# --------------------------------------------------------

name: Pull Request Review Setup

# Runs on every PR in main branch.
on: 
  pull_request:

    # Types are the actions that trigger the webhook event.
    types: [opened, reopened, synchronize]

    branches:
      - main
      
permissions:
  contents: write

jobs:
  POST-to-Azure-DevOps-API:

    # Workflow is run on an Ubuntu container hosted by GitHub. It is a new
    # container each time with ephemeral memory.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Round-Robin File
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: |
            .github/workflows/data/round-robin-file
          sparse-checkout-cone-mode: false

      - name: Get Next Team Member
        run: |
          echo "round-robin-file before team member selection:"
          cat .github/workflows/data/round-robin-file

          # Get first line -> move all but first line to temp file -> append first line
          # to temp file -> replace original team member file with temp file.

          chosen_member=$(head -n 1 .github/workflows/data/round-robin-file)
          tail -n +2 .github/workflows/data/round-robin-file > tmp
          echo $chosen_member >> tmp
          mv tmp .github/workflows/data/round-robin-file
          echo "RND_USER=${chosen_member}" >> $GITHUB_ENV

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "round-robin-file CHANGED"
          git push

          echo "round-robin-file after team member selection:"
          cat .github/workflows/data/round-robin-file

      - name: Create Task
        env:
          PAT_TOKEN:  "${{ secrets.AZUREDEVOPSPAT }}"

          # URI Params
          ORG:        "redbackoperations"
          PROJECT:    "Cybersecurity"
          TEAM:       "SecDevOps"
          API_VER:    "api-version=7.1"
          NOTIF:      "suppressNotifications={true}"
          TYPE:       "task"

          USER:       "${RND_USER}"
          PR_TITLE:   "PR: ${{ github.event.pull_request.title }}"
          LINK:       "${{ github.event.pull_request.url}}"
          TASK_DESC:  "${{ github.event.pull_request.body}} --> ${LINK}"
          AREA_PATH:  "Cybersecurity\\SecDevOps Team\\Pull Requests"
          TAG:        "PR"

        run: |
          curl -X POST \
          --header "Authorization: Bearer $PAT_TOKEN" \
          --header "Content-Type: application/json-patch+json" \
          --data '[ 
            {
              "op": "add",
              "path": "/fields/System.Title",
              "from": null,
              "value": "'${PR_TITLE}'"
            },
            {
              "op": "add",
              "path": "/fields/System.AssignedTo",
              "from": null,
              "value": "'${USER}'"
            },
            {
              "op": "add",
              "path": "/fields/System.Description",
              "from": null,
              "value": "'${TASK_DESC}'"
            },
            {
              "op": "add",
              "path": "/fields/System.AreaPath",
              "from": null,
              "value": "'${AREA_PATH}'"
            },
            {
              "op": "add",
              "path": "/fields/System.Tag",
              "from": null,
              "value": "'${TAG}'"
            }
            ]' \
          "https://dev.azure.com/${ORG}/${PROJECT}/_apis/wit/workitems/\$${TYPE}?${NOTIF}&${API_VER}" \
          | jq
