# --------------------------------------------------------
#   File:         PR_Review_Automation.yaml
#   Author:       Codey Funston [s222250824@deakin.edu.au]
# 
#   Description:  Creates Azure DevOps task for each PR
#                 in repo. Randomly assigns a team 
#                 member to review.
# --------------------------------------------------------

name: Pull Request Review Setup

# Runs on every PR in main branch.
on: [pull_request]

jobs:
  Create-task:
    # name: Create PR Task in Azure DevOps
    runs-on: windows-latest
    steps:
    #   - name: Checkout PR Preferences CSV
    #     uses: actions/checkout@v4
    #     with:
    #       sparse-checkout: |
    #         .github/workflows/data/PR_Prefernces.csv
    #       sparse-checkout-cone-mode: false

        - name: Get Next Team Member
          shell: pwsh
          env:
            REPO: "${{ github.repository}}"
          run: |
            Write-Host "${REPO}"


      # - name: Create Task
      #   env:
      #     PAT_TOKEN:  "${{ secrets.AZUREDEVOPSPAT }}"

      #     # URI Params
      #     ORG:        "redbackoperations"
      #     PROJECT:    "Cybersecurity"
      #     TEAM:       "SecDevOps"
      #     API_VER:    "api-version=7.1"
      #     NOTIF:      "suppressNotifications={true}"
      #     TYPE:       "task"

      #     USER:       "${RND_USER}"
      #     PR_TITLE:   "PR: ${{ github.event.pull_request.title }}"
      #     LINK:       "${{ github.event.pull_request.url}}"
      #     TASK_DESC:  "${{ github.event.pull_request.body}} --> ${LINK}"
      #     AREA_PATH:  "Cybersecurity\\SecDevOps Team\\Pull Requests"
      #     TAG:        "PR"

      #   run: |
      #     curl -X POST \
      #     --header "Authorization: Bearer $PAT_TOKEN" \
      #     --header "Content-Type: application/json-patch+json" \
      #     --data '[ 
      #       {
      #         "op": "add",
      #         "path": "/fields/System.Title",
      #         "from": null,
      #         "value": "'${PR_TITLE}'"
      #       },
      #       {
      #         "op": "add",
      #         "path": "/fields/System.AssignedTo",
      #         "from": null,
      #         "value": "'${USER}'"
      #       },
      #       {
      #         "op": "add",
      #         "path": "/fields/System.Description",
      #         "from": null,
      #         "value": "'${TASK_DESC}'"
      #       },
      #       {
      #         "op": "add",
      #         "path": "/fields/System.AreaPath",
      #         "from": null,
      #         "value": "'${AREA_PATH}'"
      #       },
      #       {
      #         "op": "add",
      #         "path": "/fields/System.Tag",
      #         "from": null,
      #         "value": "'${TAG}'"
      #       }
      #       ]' \
      #     "https://dev.azure.com/${ORG}/${PROJECT}/_apis/wit/workitems/\$${TYPE}?${NOTIF}&${API_VER}" \
      #     | jq

